### ISSUE TITLE
Connect to database

### ISSUE THREAD

**Issue by ethanjweiner** [Ethanweiner20/bloom_share#19]
- [x] #20
- [x] #21
- [x] #22
- [x] #23
- [x] #24
- [x] #31
- [x] #32
- [x] #25
- [x] #26
- Custom plant insertion?

Remember to:
- Code first, refactor after
- Retain existing interface as much as possible (don't create more work than is needed)
- Set up a schema for usage by others
- Still allow for an "experimental user" so participants need not use their own credentials
- Log queries using the `logger`
- Perform injection properly
- Keep some logic in the session: session ID for the signed-in user, flash logic, etc.

**Comment by Ethanweiner20** [comment]
- [ ] Create a conceptual schema for **plants** and **users**
- [ ] Extract plant storage logic to a separate class (**adapter pattern**)
- [ ] Setup application for database usage
- [ ] Re-implement plant storage logic w/ a relational database (csv -> sql): `Plants` class?
- [ ] Re-implement user storage logic w/ a relational database: `Users` class?
- [ ] Perform database optimizations
- [ ] Set up a production database and deploy to a new app

Remember to:
- Code first, refactor after
- Retain existing interface as much as possible (don't create more work than is needed)
- Log queries using the `logger`
- Perform injection properly
- Keep some logic in the session: session ID for the signed-in user, flash logic, etc.
